language: node_js 
node_js:
  - "4.4.0"
cache:
  directories:
  - node_modules
before_script:
  - npm install -g gulp
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "465e317869b8"
  - COMMIT_AUTHOR_EMAIL: "gruszecki.jakub@gmail.com"