language: node_js 
node_js:
  - "0.12"
cache:
  directories:
  - elm-stuff
  - node_modules
before_script:
  - npm install -g gulp
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "465e317869b8"
  - COMMIT_AUTHOR_EMAIL: "gruszecki.jakub@gmail.com"